### ISSUE TITLE
Broken Pipe error on Macos

### ISSUE THREAD

**Issue by wishinghand** [walle/gimli#89]
I used the `sudo gem install gimli` command to install Gimli on my Macos ( Sierra 10.12.4 ). 

Ruby version is: `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]` (maybe this is out of date?)

When I go into a folder full of only markdown files and run `gimli` I get this output:

```
/Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/wkhtmltopdf.rb:20:in `write': Broken pipe (Errno::EPIPE)
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/wkhtmltopdf.rb:20:in `puts'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/wkhtmltopdf.rb:20:in `block in output_pdf'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/wkhtmltopdf.rb:19:in `popen'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/wkhtmltopdf.rb:19:in `output_pdf'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/converter.rb:70:in `output_pdf'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/converter.rb:38:in `block in convert!'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/converter.rb:31:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli/converter.rb:31:in `convert!'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/lib/gimli.rb:31:in `process!'
	from /Library/Ruby/Gems/2.0.0/gems/gimli-0.5.9/bin/gimli:25:in `<top (required)>'
	from /usr/local/bin/gimli:23:in `load'
	from /usr/local/bin/gimli:23:in `<main>'
```

I tried looking at the files mentioned in the stack but I am not a Ruby programmer so I couldn't really make sense of it. Any advice? Am I making an obvious n00b mistake here?

**Comment by wishinghand** [comment]
I figured it out. The issue was `wkhtmltopdf`. It needed to be installed. I used `brew install wkhtmltopdf` and that worked out perfect.
